description "Kindle native reading time tracker"

start on framework_ready
stop on stopping framework

respawn
respawn limit 5 60
console none

script
    exec /mnt/us/reading-time/bin/native-reading-time-daemon.sh >>/mnt/us/reading-time/upstart.log 2>&1
end script